CREATE TABLE [dbo].[FileTask]
(
	[FileGUID] VARCHAR(36) NOT NULL , 
    [TaskID] INT NOT NULL, 
    PRIMARY KEY ([TaskID], [FileGUID]), 
    CONSTRAINT [FK_FileTask_ToFile] FOREIGN KEY ([FileGUID]) REFERENCES [File]([GUID]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_FileTask_ToTask] FOREIGN KEY ([TaskID]) REFERENCES [Task]([ID]) ON DELETE CASCADE ON UPDATE CASCADE
)
